language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install -r requirements/development.txt
before_script:
  - python manage.py migrate
  - flake8 fibonacci
script:
  - python manage.py test
